import { ApiError } from '../errors';
import type { Repository } from '../repositories/types';
import type { Cashflow, ExecuteInvestmentPlansOutput, Holding, InvestmentPlan, Price } from '../types';
import { addDays, calculateNextRunDate, compareDate } from '../utils/date';

export async function executeDueInvestmentPlans(input: {
  repo: Repository;
  userId?: string;
  date: string;
  now: string;
}): Promise<ExecuteInvestmentPlansOutput> {
  const plans = (await input.repo.list('investment_plans', (plan) => {
    if (input.userId && plan.userId !== input.userId) {
      return false;
    }
    return plan.status === 'ACTIVE' && Boolean(plan.nextRunDate) && compareDate(plan.nextRunDate as string, input.date) <= 0;
  })).sort((a, b) => (a.nextRunDate ?? '').localeCompare(b.nextRunDate ?? ''));

  const output: ExecuteInvestmentPlansOutput = {
    date: input.date,
    createdCashflowIds: [],
    confirmedCashflowIds: [],
    skippedPlanIds: []
  };

  for (const plan of plans) {
    const runDate = plan.nextRunDate;
    if (!runDate) {
      output.skippedPlanIds.push(plan._id);
      continue;
    }

    const holding = await input.repo.get('holdings', plan.holdingId);
    if (!holding || holding.userId !== plan.userId || !holding.active) {
      output.skippedPlanIds.push(plan._id);
      continue;
    }

    const cashflowId = `${plan._id}_${runDate}`;
    const existing = await input.repo.get('cashflows', cashflowId);
    if (!existing) {
      const price = await latestPrice(input.repo, 'FUND', holding.symbol, runDate);
      const feeAmount = roundMoney(plan.amountPerPeriod * (plan.feeRate ?? 0));
      const quantity = price ? roundQuantity((plan.amountPerPeriod - feeAmount) / price.price) : undefined;
      const status: Cashflow['status'] = price ? 'CONFIRMED' : 'PENDING';
      const cashflow: Cashflow = {
        _id: cashflowId,
        userId: plan.userId,
        accountId: plan.accountId,
        holdingId: plan.holdingId,
        planId: plan._id,
        type: 'BUY',
        amount: plan.amountPerPeriod,
        currency: plan.currency,
        quantity,
        confirmedPrice: price?.price,
        feeAmount,
        tradeDate: runDate,
        note: `Generated by investment plan ${plan.name}`,
        source: 'PLAN',
        status,
        createdAt: input.now,
        updatedAt: input.now
      };
      await input.repo.set('cashflows', cashflow);
      output.createdCashflowIds.push(cashflowId);

      if (status === 'CONFIRMED' && quantity !== undefined) {
        await confirmPlanUnits(input.repo, holding, plan, quantity, input.now);
        output.confirmedCashflowIds.push(cashflowId);
      }
    }

    const nextRunDate = calculateNextRunDate({
      frequency: plan.frequency,
      startDate: plan.startDate,
      fromDate: addDays(runDate, 1),
      dayOfWeek: plan.dayOfWeek,
      dayOfMonth: plan.dayOfMonth,
      endDate: plan.endDate
    });
    await input.repo.patch('investment_plans', plan._id, {
      nextRunDate,
      status: nextRunDate ? plan.status : 'ENDED',
      updatedAt: input.now
    });
  }

  return output;
}

export function nextRunForPlan(plan: Pick<InvestmentPlan, 'frequency' | 'startDate' | 'dayOfWeek' | 'dayOfMonth' | 'endDate' | 'status'>, fromDate: string): string | null {
  if (plan.status !== 'ACTIVE') {
    return null;
  }
  return calculateNextRunDate({
    frequency: plan.frequency,
    startDate: plan.startDate,
    fromDate,
    dayOfWeek: plan.dayOfWeek,
    dayOfMonth: plan.dayOfMonth,
    endDate: plan.endDate
  });
}

async function latestPrice(repo: Repository, assetType: Price['assetType'], symbol: string, date: string): Promise<Price | undefined> {
  const prices = (await repo.list('prices', (price) => price.assetType === assetType && price.symbol === symbol && price.date <= date))
    .sort((a, b) => b.date.localeCompare(a.date));
  return prices[0];
}

async function confirmPlanUnits(repo: Repository, holding: Holding, plan: InvestmentPlan, quantity: number, now: string): Promise<void> {
  if (quantity <= 0 || !Number.isFinite(quantity)) {
    throw new ApiError('INVALID_PLAN_QUANTITY', `Calculated non-positive quantity for plan ${plan._id}`, { status: 422 });
  }
  await repo.patch('holdings', holding._id, {
    quantity: roundQuantity(holding.quantity + quantity),
    costAmount: roundMoney(holding.costAmount + plan.amountPerPeriod),
    updatedAt: now
  });
}

function roundMoney(value: number): number {
  return Math.round((value + Number.EPSILON) * 100) / 100;
}

function roundQuantity(value: number): number {
  return Math.round((value + Number.EPSILON) * 1_000_000) / 1_000_000;
}
